### ISSUE TITLE
Better looking cards on listing page

### ISSUE THREAD

**Issue by KajalDeore04** [rajnish032/Wanderlust#3]
I want to style the cards that are being displayed on the listing page 
please assign this issue to me under SWOC (Social Winter of Code)
I will be able to contribute after 1st of Jan as it counts then..

![image](https://github.com/user-attachments/assets/048d1881-901e-4aaf-bc63-22df96ee706e)

**Comment by YogyashriPatil** [comment]
Hi , I have some ideas to enhance the user experience on the listing page for the hotel management website by designing better-looking cards. My proposed design includes:
Rounded edges for a modern look.
Subtle shadows to add depth and make the cards visually appealing.
A clean layout showcasing hotel images, name, key amenities, pricing, and a prominent "Book Now" button.
A soft color palette with minimalistic backgrounds to emphasize the content on the cards.
I believe this design update will significantly improve user engagement. Could I get permission to contribute and implement this enhancement? Let me know if there are any specific design guidelines I should follow.

Looking forward to your response!
Best regards, Yogyashri patil

**Comment by YogyashriPatil** [comment]
Hi team,

I'm happy to add some code to address the task "Wanderlust". I'll start
working on it and keep you updated on my progress. I have submitted this
under the Social Winter of Code (SWOC). If you have any questions or need
to discuss further, feel free to reach out to me at
***@***.*** Looking forward to contributing to this project!

Best regards, Yogyashri Patil
